project_name: tunnel
before:
  hooks:
    - go mod download
builds:
  - main: cmd/tunnel/main.go
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
archives:
  - replacements:
      darwin: macos
      amd64: 64-bit
      386: 32-bit
    format_overrides:
      - goos: windows
        format: zip
nfpms:
  - formats:
      - deb
      - rpm
    replacements:
      amd64: 64-bit
      386: 32-bit
    vendor: "LabStack"
    homepage: "https://tunnel.labstack.com"
    maintainer: "Vishal Rana <vr@labstack.com>"
    description: "Tunnel lets you expose local servers to the internet securely - ngrok alternative, compatible with SSH
    client."
    license: "MIT"
checksum:
  name_template: "checksum.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  draft: true
